# -*- coding: utf-8 -*-
"""
Reads Karaoke_Song_Database.xlsx and writes songs.js for the web app.

Run this after every edit to the Excel file:

    python3 build.py

Then commit songs.js (and index.html) to GitHub. songs.js is loaded by
index.html as a plain <script>, so the app works both from a local file and
from GitHub Pages -- no server needed.
"""

import json
import os
import sys
from datetime import datetime

from openpyxl import load_workbook

HERE = os.path.dirname(os.path.abspath(__file__))
XLSX = os.path.join(HERE, "Karaoke_Song_Database.xlsx")
OUT = os.path.join(HERE, "songs.js")

HEAD_ROW = 5
FIRST_COL = 2

VALID_CATEGORY = {"warm-up": "Warm-Up", "hype": "Hype", "closer": "Closer"}
VALID_DIFFICULTY = {"easy": "Easy", "medium": "Medium", "hard": "Hard", "legend": "Legend"}
VALID_FORMAT = {"solo": "Solo", "duet": "Duet", "group": "Group"}


def norm(value, table, default, label, row, warnings):
    if value is None or str(value).strip() == "":
        return default
    key = str(value).strip().lower()
    if key in table:
        return table[key]
    warnings.append(f"row {row}: unrecognised {label} '{value}' — using '{default}'")
    return default


def clamp(value, lo, hi, default, label, row, warnings):
    try:
        n = int(float(value))
    except (TypeError, ValueError):
        if value not in (None, ""):
            warnings.append(f"row {row}: {label} '{value}' is not a number — using {default}")
        return default
    if n < lo or n > hi:
        warnings.append(f"row {row}: {label} {n} out of range {lo}-{hi} — clamped")
        return max(lo, min(hi, n))
    return n


def main():
    if not os.path.exists(XLSX):
        print(f"Can't find {os.path.basename(XLSX)}.")
        print("Run 'python3 seed_database.py' first to create it.")
        return 1

    wb = load_workbook(XLSX, data_only=True)
    if "Songs" not in wb.sheetnames:
        print("The workbook has no sheet called 'Songs'.")
        return 1
    ws = wb["Songs"]

    headers = {}
    for col in range(FIRST_COL, ws.max_column + 1):
        name = ws.cell(row=HEAD_ROW, column=col).value
        if name:
            headers[str(name).strip()] = col

    required = ["Category", "Song Title", "Artist"]
    missing = [h for h in required if h not in headers]
    if missing:
        print(f"Missing required column(s) in the Songs sheet: {', '.join(missing)}")
        return 1

    def get(row, name):
        col = headers.get(name)
        return ws.cell(row=row, column=col).value if col else None

    songs = []
    warnings = []
    skipped = 0
    seen_ids = set()

    for row in range(HEAD_ROW + 1, ws.max_row + 1):
        title = get(row, "Song Title")
        artist = get(row, "Artist")
        if not title or not str(title).strip():
            continue  # blank row -- ignore silently

        active = str(get(row, "Active") or "Y").strip().upper()
        if active.startswith("N"):
            skipped += 1
            continue

        category = norm(get(row, "Category"), VALID_CATEGORY, "Hype", "Category", row, warnings)

        sid = str(get(row, "ID") or "").strip() or f"R{row:04d}"
        if sid in seen_ids:
            sid = f"{sid}-{row}"
            warnings.append(f"row {row}: duplicate ID — renamed to '{sid}'")
        seen_ids.add(sid)

        year_raw = get(row, "Year")
        try:
            year = int(float(year_raw)) if year_raw not in (None, "") else None
        except (TypeError, ValueError):
            year = None
            warnings.append(f"row {row}: year '{year_raw}' isn't a number — left blank")

        songs.append({
            "id": sid,
            "cat": category,
            "title": str(title).strip(),
            "artist": str(artist).strip() if artist else "Unknown",
            "year": year,
            "genre": str(get(row, "Genre") or "").strip() or "Pop",
            "energy": clamp(get(row, "Energy"), 1, 5, 3, "Energy", row, warnings),
            "difficulty": norm(get(row, "Difficulty"), VALID_DIFFICULTY, "Medium", "Difficulty", row, warnings),
            "format": norm(get(row, "Format"), VALID_FORMAT, "Solo", "Format", row, warnings),
            "range": str(get(row, "Vocal Range") or "").strip() or "Mid",
            "crowd": clamp(get(row, "Crowd"), 1, 5, 3, "Crowd", row, warnings),
            "notes": str(get(row, "Notes") or "").strip(),
        })

    if not songs:
        print("No active songs found — nothing written. Check the Active column.")
        return 1

    counts = {c: sum(1 for s in songs if s["cat"] == c) for c in ("Warm-Up", "Hype", "Closer")}
    empty = [c for c, n in counts.items() if n == 0]

    payload = {
        "generated": datetime.now().strftime("%d %b %Y, %H:%M"),
        "counts": counts,
        "songs": songs,
    }

    banner = (
        "// AUTO-GENERATED by build.py — do not edit by hand.\n"
        "// Source of truth: Karaoke_Song_Database.xlsx\n"
        f"// Last built: {payload['generated']}\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(banner)
        f.write("const SONG_DB = ")
        f.write(json.dumps(payload, ensure_ascii=False, indent=1))
        f.write(";\n")

    print(f"Wrote songs.js — {len(songs)} active songs")
    for c in ("Warm-Up", "Hype", "Closer"):
        print(f"  {c:<9} {counts[c]:>3}")
    if skipped:
        print(f"  (skipped {skipped} row(s) marked Active = N)")
    if empty:
        print("\nHeads up: no songs in " + ", ".join(empty) +
              ". That phase will show an empty state in the app.")
    if warnings:
        print(f"\n{len(warnings)} warning(s):")
        for w in warnings[:20]:
            print(f"  - {w}")
        if len(warnings) > 20:
            print(f"  ... and {len(warnings) - 20} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
