# -*- coding: utf-8 -*-
"""
Seed data for the Karaoke Night song database.

This is the starting compilation only. Once the .xlsx exists, EDIT THE EXCEL FILE
-- not this file. Re-running seed_database.py will overwrite your Excel edits.

Column meanings:
  energy      1-5  how much the song lifts the room
  difficulty  Easy | Medium | Hard | Legend   (Legend = only attempt with confidence)
  format      Solo | Duet | Group
  range       Low | Low-Mid | Mid | Mid-High | High | Wide
  crowd       1-5  how likely the room sings along with you
"""

# (title, artist, year, genre, energy, difficulty, format, range, crowd, notes)

WARM_UP = [
    ("Sweet Caroline", "Neil Diamond", 1969, "Classic Pop", 3, "Easy", "Group", "Mid", 5, "The 'ba-ba-baaa' is automatic. Impossible to fail."),
    ("Wonderwall", "Oasis", 1995, "Britpop", 3, "Easy", "Group", "Mid", 5, "Everyone knows it. Nobody hits the nasal tone. Nobody cares."),
    ("Take Me Home, Country Roads", "John Denver", 1971, "Country", 3, "Easy", "Group", "Mid", 5, "Universal opener. Works in any country on earth."),
    ("Stand By Me", "Ben E. King", 1961, "Soul", 2, "Easy", "Solo", "Mid", 4, "Slow, forgiving, and instantly warm. Great first-song-of-the-night."),
    ("Brown Eyed Girl", "Van Morrison", 1967, "Classic Rock", 3, "Easy", "Group", "Mid", 5, "Sha-la-la section does the heavy lifting for you."),
    ("I'm Yours", "Jason Mraz", 2008, "Acoustic Pop", 3, "Easy", "Solo", "Mid", 4, "Breezy and low-stakes. Watch the fast wordy bits."),
    ("Riptide", "Vance Joy", 2013, "Indie Folk", 3, "Easy", "Group", "Mid", 4, "Three chords of pure goodwill."),
    ("Ho Hey", "The Lumineers", 2012, "Indie Folk", 3, "Easy", "Group", "Mid", 4, "The 'HO!' and 'HEY!' give the room a job to do."),
    ("Hey There Delilah", "Plain White T's", 2006, "Acoustic Pop", 2, "Easy", "Solo", "Mid-High", 4, "Gentle and nostalgic. Sneaky high notes in the bridge."),
    ("Budapest", "George Ezra", 2014, "Indie Pop", 3, "Medium", "Solo", "Low", 3, "Rewards a low, resonant voice. Sit into your chest register."),
    ("Free Fallin'", "Tom Petty", 1989, "Classic Rock", 3, "Easy", "Group", "Mid", 5, "Four chords, one chorus, everyone in."),
    ("Learning to Fly", "Tom Petty", 1991, "Classic Rock", 3, "Easy", "Solo", "Mid", 3, "Mellow, steady, no traps anywhere."),
    ("Banana Pancakes", "Jack Johnson", 2005, "Acoustic", 2, "Easy", "Solo", "Low-Mid", 3, "Sunday-morning energy. Good for settling the room."),
    ("Sunday Morning", "Maroon 5", 2004, "Pop Soul", 3, "Medium", "Solo", "Mid", 3, "Jazzy and smooth. Groove matters more than power here."),
    ("Fast Car", "Tracy Chapman", 1988, "Folk Rock", 3, "Medium", "Solo", "Low-Mid", 4, "Storytelling song. Sell the words, not the notes."),
    ("Killing Me Softly With His Song", "Fugees", 1996, "R&B", 3, "Medium", "Solo", "Mid", 4, "The 'one time, two time' ad-libs are free crowd points."),
    ("Someone Like You", "Adele", 2011, "Pop Ballad", 3, "Hard", "Solo", "Mid-High", 5, "Emotionally huge but vocally exposed. Warm up first."),
    ("Just the Way You Are", "Bruno Mars", 2010, "Pop", 3, "Medium", "Solo", "Mid-High", 4, "Sweet and safe. Chorus sits higher than people expect."),
    ("Perfect", "Ed Sheeran", 2017, "Pop Ballad", 2, "Medium", "Duet", "Mid", 4, "The modern wedding-slow-dance song. Lovely as a duet."),
    ("Thinking Out Loud", "Ed Sheeran", 2014, "Pop Soul", 2, "Medium", "Solo", "Mid", 4, "Slow burn. Save the big note for the last chorus."),
    ("Photograph", "Ed Sheeran", 2014, "Pop Ballad", 2, "Easy", "Solo", "Mid", 3, "Tender and easy on the voice. Good second song."),
    ("Say You Won't Let Go", "James Arthur", 2016, "Pop Ballad", 3, "Medium", "Solo", "Mid-High", 4, "Big-hearted. The last chorus goes up a gear."),
    ("Islands in the Stream", "Kenny Rogers & Dolly Parton", 1983, "Country Pop", 3, "Easy", "Duet", "Mid", 5, "The greatest low-effort duet ever written. Grab a partner."),
    ("Lucky", "Jason Mraz & Colbie Caillat", 2008, "Acoustic Pop", 2, "Easy", "Duet", "Mid", 3, "Whistle-friendly and charming. Zero pressure."),
    ("Creep", "Radiohead", 1992, "Alt Rock", 3, "Medium", "Solo", "Mid-High", 5, "Quiet-quiet-LOUD. The room shouts the chorus with you."),
    ("Zombie", "The Cranberries", 1994, "Alt Rock", 4, "Hard", "Solo", "Mid-High", 5, "That yodel-growl is a whole technique. Glorious when it lands."),
    ("With or Without You", "U2", 1987, "Rock", 3, "Medium", "Solo", "Mid-High", 4, "Builds slowly. Hold back for three minutes, then let go."),
    ("More Than Words", "Extreme", 1990, "Acoustic Rock", 2, "Hard", "Duet", "High", 4, "Deceptively brutal harmonies. Attempt with a good partner."),
    ("Wish You Were Here", "Pink Floyd", 1975, "Classic Rock", 2, "Easy", "Group", "Low-Mid", 4, "Everyone hums the intro. Gentle and communal."),
    ("Yellow", "Coldplay", 2000, "Alt Rock", 3, "Medium", "Group", "High", 5, "Falsetto chorus. Commit fully or it collapses."),
    ("The Scientist", "Coldplay", 2002, "Alt Rock", 2, "Medium", "Solo", "Mid-High", 4, "Beautiful and sad. Nice palate cleanser early on."),
    ("Drops of Jupiter", "Train", 2001, "Pop Rock", 3, "Medium", "Group", "Mid-High", 4, "The 'na-na-na' outro is a guaranteed singalong."),
    ("Blackbird", "The Beatles", 1968, "Classic Rock", 2, "Easy", "Solo", "Mid", 3, "Short, pretty, and impossible to embarrass yourself with."),
    ("Landslide", "Fleetwood Mac", 1975, "Soft Rock", 2, "Medium", "Solo", "Mid", 4, "Quietly devastating. Perfect for a small early crowd."),
    ("Dreams", "Fleetwood Mac", 1977, "Soft Rock", 3, "Easy", "Solo", "Mid", 4, "Hypnotic groove. Just float on top of it."),
    ("Tiny Dancer", "Elton John", 1971, "Classic Rock", 3, "Medium", "Group", "Mid-High", 5, "The last chorus turns the whole room into a choir."),
    ("Your Song", "Elton John", 1970, "Classic Rock", 2, "Medium", "Solo", "Mid", 4, "Warm, wordy, and always welcome."),
    ("Bubbly", "Colbie Caillat", 2007, "Acoustic Pop", 2, "Easy", "Solo", "Mid", 3, "Feather-light. Good for a nervous first-timer."),
    ("Sweet Home Alabama", "Lynyrd Skynyrd", 1974, "Southern Rock", 4, "Easy", "Group", "Mid", 5, "Riff arrives, room wakes up. Bridge into the hype hour."),
    ("Wagon Wheel", "Darius Rucker", 2013, "Country", 3, "Easy", "Group", "Mid", 4, "Rolling singalong chorus. Country night starter kit."),
    ("Big Yellow Taxi", "Joni Mitchell", 1970, "Folk", 3, "Easy", "Group", "Mid", 3, "Short, bouncy, and full of 'ooo bop bop bop'."),
    ("Ain't No Sunshine", "Bill Withers", 1971, "Soul", 2, "Easy", "Solo", "Low-Mid", 4, "Twenty-six 'I know's. Count them, the crowd will."),
    ("Lean on Me", "Bill Withers", 1972, "Soul", 3, "Easy", "Group", "Mid", 5, "Arms around shoulders. Works at any hour, honestly."),
    ("What's Up?", "4 Non Blondes", 1992, "Alt Rock", 4, "Medium", "Group", "Mid-High", 5, "The 'HEY YEAH YEAH' is a room-wide event."),
    ("Torn", "Natalie Imbruglia", 1997, "Pop Rock", 3, "Easy", "Solo", "Mid", 5, "Everyone born before 2000 knows every word."),
]

HYPE = [
    ("Livin' on a Prayer", "Bon Jovi", 1986, "Rock Anthem", 5, "Hard", "Group", "High", 5, "That key change is a cliff. Jump anyway. The room will carry you."),
    ("Don't Stop Believin'", "Journey", 1981, "Rock Anthem", 5, "Hard", "Group", "High", 5, "Two minutes of patience, then the biggest payoff in karaoke."),
    ("Mr. Brightside", "The Killers", 2003, "Indie Rock", 5, "Medium", "Group", "Mid-High", 5, "Legally a group activity. Nobody sits down for this one."),
    ("Bohemian Rhapsody", "Queen", 1975, "Rock Opera", 5, "Legend", "Group", "Wide", 5, "Six minutes, four genres. Bring friends for the opera bit."),
    ("Africa", "Toto", 1982, "Soft Rock", 4, "Medium", "Group", "Mid-High", 5, "Blessing the rains is a shared responsibility."),
    ("Sweet Child o' Mine", "Guns N' Roses", 1987, "Hard Rock", 5, "Hard", "Solo", "High", 5, "The 'where do we go now' outro is a stamina test."),
    ("Summer of '69", "Bryan Adams", 1984, "Rock", 5, "Medium", "Group", "Mid-High", 5, "Raspy, joyful, fist-pumping. Nearly foolproof."),
    ("Jessie's Girl", "Rick Springfield", 1981, "Power Pop", 4, "Medium", "Group", "Mid-High", 4, "Pure 80s adrenaline with a chorus everyone remembers."),
    ("Take On Me", "a-ha", 1985, "Synth Pop", 5, "Legend", "Group", "High", 5, "That final note has ended careers. Go for it anyway."),
    ("Total Eclipse of the Heart", "Bonnie Tyler", 1983, "Power Ballad", 5, "Hard", "Group", "Wide", 5, "Turn around, bright eyes. Full theatre required."),
    ("Eye of the Tiger", "Survivor", 1982, "Rock Anthem", 5, "Medium", "Group", "Mid-High", 5, "Instant montage energy. Everyone stands up."),
    ("Pour Some Sugar on Me", "Def Leppard", 1987, "Hair Metal", 5, "Medium", "Group", "Mid-High", 4, "Swagger over accuracy. Lean into it."),
    ("Smells Like Teen Spirit", "Nirvana", 1991, "Grunge", 5, "Medium", "Group", "Mid", 5, "Mumble the verses like everyone else, then scream."),
    ("Basket Case", "Green Day", 1994, "Punk Rock", 5, "Medium", "Group", "Mid-High", 4, "Fast words, huge payoff. Breathe on the downbeats."),
    ("American Idiot", "Green Day", 2004, "Punk Rock", 5, "Medium", "Group", "Mid-High", 4, "Angry and cathartic. Great for clearing the cobwebs."),
    ("Song 2", "Blur", 1997, "Alt Rock", 5, "Easy", "Group", "Mid", 4, "Two minutes. Mostly 'WOO-HOO'. Best effort-to-reward ratio here."),
    ("Semi-Charmed Life", "Third Eye Blind", 1997, "Alt Rock", 4, "Hard", "Solo", "Mid-High", 4, "Verses are a tongue-twister sprint. Chorus is a reward."),
    ("All Star", "Smash Mouth", 1999, "Pop Rock", 4, "Easy", "Group", "Mid", 5, "Somebody once told me the room would lose it. They were right."),
    ("Dancing Queen", "ABBA", 1976, "Disco", 5, "Hard", "Group", "High", 5, "Higher than it sounds. Worth every strained note."),
    ("Mamma Mia", "ABBA", 1975, "Pop", 5, "Medium", "Group", "Mid-High", 5, "Relentlessly happy. Choreography optional but encouraged."),
    ("I Will Survive", "Gloria Gaynor", 1978, "Disco", 5, "Medium", "Group", "Mid-High", 5, "The spoken intro sets up the whole room. Milk it."),
    ("YMCA", "Village People", 1978, "Disco", 5, "Easy", "Group", "Mid", 5, "You don't sing this one so much as conduct it."),
    ("September", "Earth, Wind & Fire", 1978, "Funk", 5, "Hard", "Group", "High", 5, "Ba-de-ya. Ridiculously high. Nobody minds."),
    ("Superstition", "Stevie Wonder", 1972, "Funk", 4, "Hard", "Solo", "Mid-High", 4, "The groove is everything. Don't rush the phrasing."),
    ("Billie Jean", "Michael Jackson", 1982, "Pop", 4, "Hard", "Solo", "High", 5, "Rhythmically tricky and high. Immaculate if you nail it."),
    ("Beat It", "Michael Jackson", 1982, "Rock Pop", 5, "Hard", "Group", "High", 5, "Attitude carries this one further than range does."),
    ("Thriller", "Michael Jackson", 1982, "Pop", 5, "Medium", "Group", "Mid-High", 5, "Six minutes with a built-in dance break. Use it."),
    ("Girls Just Want to Have Fun", "Cyndi Lauper", 1983, "Pop", 5, "Medium", "Group", "Mid-High", 5, "Pure serotonin. Nobody stays seated."),
    ("Wake Me Up Before You Go-Go", "Wham!", 1984, "Pop", 5, "Medium", "Group", "Mid-High", 5, "Jitterbug. The whole room does the hand thing."),
    ("Footloose", "Kenny Loggins", 1984, "Pop Rock", 5, "Medium", "Group", "Mid-High", 4, "Built for kicking off Sunday shoes."),
    ("Livin' La Vida Loca", "Ricky Martin", 1999, "Latin Pop", 5, "Hard", "Group", "Mid-High", 4, "Breathless verses, brass-band chorus. Hips help."),
    ("...Baby One More Time", "Britney Spears", 1998, "Pop", 4, "Medium", "Group", "Mid", 5, "'Oh baby, baby' — the room finishes the line for you."),
    ("Toxic", "Britney Spears", 2003, "Pop", 5, "Hard", "Solo", "High", 5, "Those strings, that breathy chorus. Iconic and difficult."),
    ("I Want It That Way", "Backstreet Boys", 1999, "Pop", 4, "Medium", "Group", "Mid-High", 5, "The lyrics make no sense. Sing them like scripture."),
    ("Everybody (Backstreet's Back)", "Backstreet Boys", 1997, "Pop", 5, "Medium", "Group", "Mid", 4, "Am I original? Yeah. Am I the only one? No, the room joined in."),
    ("Bye Bye Bye", "NSYNC", 2000, "Pop", 5, "Medium", "Group", "Mid-High", 5, "The arm choreography is non-negotiable."),
    ("Wannabe", "Spice Girls", 1996, "Pop", 5, "Hard", "Group", "Mid", 5, "The rap bit separates the prepared from the brave."),
    ("Say My Name", "Destiny's Child", 1999, "R&B", 4, "Hard", "Group", "Mid-High", 4, "Rapid-fire R&B phrasing. Split the parts three ways."),
    ("No Scrubs", "TLC", 1999, "R&B", 4, "Medium", "Group", "Mid", 5, "Attitude anthem. Every word lands."),
    ("Waterfalls", "TLC", 1994, "R&B", 3, "Medium", "Group", "Mid", 4, "Smooth and soulful with a rap break to hand off."),
    ("Crazy in Love", "Beyonce", 2003, "R&B", 5, "Hard", "Group", "High", 5, "Uh-oh, uh-oh. The horns do half the work."),
    ("Yeah!", "Usher", 2004, "R&B", 5, "Medium", "Group", "Mid", 5, "Peak-hour club energy. Three vocalists' worth of parts."),
    ("Gold Digger", "Kanye West ft. Jamie Foxx", 2005, "Hip Hop", 5, "Hard", "Duet", "Mid", 5, "One rapper, one Ray Charles impression. Perfect pairing."),
    ("Hey Ya!", "OutKast", 2003, "Funk Pop", 5, "Hard", "Group", "Mid-High", 5, "Shake it like a Polaroid picture. Deceptively fast."),
    ("Umbrella", "Rihanna", 2007, "Pop R&B", 4, "Medium", "Group", "Mid", 5, "Ella-ella-eh-eh-eh. Built-in audience participation."),
    ("Since U Been Gone", "Kelly Clarkson", 2004, "Pop Rock", 5, "Hard", "Solo", "High", 5, "That chorus is a full-throated scream. Magnificent."),
    ("Rolling in the Deep", "Adele", 2010, "Soul Pop", 5, "Hard", "Group", "Mid-High", 5, "Powerhouse. The room claps the beat without being asked."),
    ("Poker Face", "Lady Gaga", 2008, "Dance Pop", 5, "Medium", "Group", "Mid", 5, "P-p-p-poker face. Robotic hook, huge response."),
    ("Bad Romance", "Lady Gaga", 2009, "Dance Pop", 5, "Hard", "Group", "Mid-High", 5, "Rah-rah-ah-ah-ah. Theatrical to the point of absurd."),
    ("Firework", "Katy Perry", 2010, "Pop", 5, "Hard", "Solo", "High", 5, "The last chorus is a mountain. Pace yourself."),
    ("Hot n Cold", "Katy Perry", 2008, "Pop", 4, "Easy", "Group", "Mid", 4, "Simple, bratty, and endlessly fun."),
    ("Tik Tok", "Kesha", 2009, "Dance Pop", 5, "Easy", "Group", "Mid", 5, "Half-rapped, all attitude. Almost impossible to sing badly."),
    ("Party in the U.S.A.", "Miley Cyrus", 2009, "Pop", 5, "Easy", "Group", "Mid", 5, "Nodding your head like yeah is mandatory."),
    ("Shake It Off", "Taylor Swift", 2014, "Pop", 5, "Medium", "Group", "Mid", 5, "Relentless. Great for resetting a flagging room."),
    ("Love Story", "Taylor Swift", 2008, "Country Pop", 4, "Medium", "Group", "Mid-High", 5, "The key change at the end is the whole point."),
    ("Shut Up and Dance", "WALK THE MOON", 2014, "Pop Rock", 5, "Medium", "Group", "Mid-High", 5, "Named after what the room is already doing."),
    ("Uptown Funk", "Mark Ronson ft. Bruno Mars", 2014, "Funk Pop", 5, "Hard", "Group", "Mid", 5, "Swagger required. The 'hot damn' call-and-response is gold."),
    ("Moves Like Jagger", "Maroon 5", 2011, "Pop", 4, "Hard", "Duet", "High", 4, "Falsetto city. The whistle hook is free entertainment."),
    ("Sugar", "Maroon 5", 2015, "Pop", 4, "Hard", "Solo", "High", 4, "Sweet and very, very high. Know your ceiling."),
    ("Can't Stop the Feeling!", "Justin Timberlake", 2016, "Pop", 5, "Medium", "Group", "Mid-High", 5, "Sunshine in song form. Zero cynicism allowed."),
    ("Shape of You", "Ed Sheeran", 2017, "Pop", 4, "Medium", "Group", "Mid", 5, "Everybody knows it whether they want to or not."),
    ("Blinding Lights", "The Weeknd", 2019, "Synth Pop", 5, "Hard", "Solo", "High", 5, "80s revival banger. Sits uncomfortably high for most."),
    ("Levitating", "Dua Lipa", 2020, "Disco Pop", 5, "Medium", "Group", "Mid", 4, "Modern disco. Keeps the floor moving."),
    ("Don't Start Now", "Dua Lipa", 2019, "Disco Pop", 5, "Medium", "Solo", "Mid-High", 4, "Sharp, sassy, and built on a bassline you can ride."),
    ("Wake Me Up", "Avicii", 2013, "Dance Folk", 5, "Medium", "Group", "Mid-High", 5, "Folk verse, festival drop. Everyone's hands go up."),
    ("Sk8er Boi", "Avril Lavigne", 2002, "Pop Punk", 5, "Medium", "Group", "Mid", 5, "He was a boy, she was a girl. Can I make it any more obvious?"),
    ("Complicated", "Avril Lavigne", 2002, "Pop Rock", 4, "Easy", "Group", "Mid", 4, "Early-2000s comfort food."),
    ("MMMBop", "Hanson", 1997, "Pop Rock", 4, "Hard", "Group", "Mid-High", 4, "The mmmbop part is gibberish at speed. Wing it joyfully."),
    ("Believe", "Cher", 1998, "Dance Pop", 5, "Medium", "Group", "Mid", 5, "Do the robot-voice bit. It's expected."),
    ("It's Raining Men", "The Weather Girls", 1982, "Disco", 5, "Hard", "Group", "High", 5, "Camp, chaotic, and enormous fun."),
    ("Ain't No Mountain High Enough", "Marvin Gaye & Tammi Terrell", 1967, "Motown", 4, "Medium", "Duet", "Mid-High", 5, "The best call-and-response duet in the book."),
    ("I Wanna Dance with Somebody", "Whitney Houston", 1987, "Pop", 5, "Hard", "Group", "High", 5, "Joy incarnate, but Whitney's range is Whitney's range."),
    ("Don't You (Forget About Me)", "Simple Minds", 1985, "New Wave", 4, "Medium", "Group", "Mid-High", 5, "The 'la la la la' outro runs forever. Bliss."),
    ("Bittersweet Symphony", "The Verve", 1997, "Britpop", 4, "Medium", "Group", "Mid", 4, "Strings do the heavy lifting. Strut through it."),
    ("Seven Nation Army", "The White Stripes", 2003, "Garage Rock", 5, "Easy", "Group", "Low-Mid", 5, "The riff is a stadium chant. Free crowd energy."),
]

CLOSERS = [
    ("My Way", "Frank Sinatra", 1969, "Standard", 4, "Hard", "Solo", "Wide", 5, "The definitive last song. Sing it like you mean every word."),
    ("Theme from New York, New York", "Frank Sinatra", 1979, "Standard", 4, "Hard", "Group", "Wide", 5, "Big finish, arms wide. The room links up for the last note."),
    ("We Are the Champions", "Queen", 1977, "Rock Anthem", 4, "Hard", "Group", "High", 5, "Lights up, everyone standing. Nothing closes harder."),
    ("The Show Must Go On", "Queen", 1991, "Rock Anthem", 4, "Legend", "Solo", "Wide", 4, "Freddie's final summit. Attempt only with your whole chest."),
    ("Piano Man", "Billy Joel", 1973, "Soft Rock", 3, "Medium", "Group", "Mid", 5, "The la-di-da chorus is the sound of a night ending well."),
    ("(I've Had) The Time of My Life", "Bill Medley & Jennifer Warnes", 1987, "Pop", 4, "Hard", "Duet", "Wide", 5, "Yes, someone will attempt the lift. No, don't."),
    ("I Will Always Love You", "Whitney Houston", 1992, "Pop Ballad", 4, "Legend", "Solo", "Wide", 5, "The 'AND IIIII' is a rite of passage. Respect it."),
    ("Purple Rain", "Prince", 1984, "Rock", 4, "Hard", "Group", "High", 5, "Eight minutes of catharsis. The 'woo-hoo-hoo' outro is communal."),
    ("Hallelujah", "Jeff Buckley", 1994, "Folk Rock", 2, "Hard", "Solo", "Wide", 5, "Room goes silent. Pick your verses; there are too many."),
    ("Let It Be", "The Beatles", 1970, "Classic Rock", 3, "Easy", "Group", "Mid", 5, "Gentle, universal, and perfectly final."),
    ("Hey Jude", "The Beatles", 1968, "Classic Rock", 4, "Easy", "Group", "Mid", 5, "Four minutes of song, three minutes of 'na-na-na'. Ideal last call."),
    ("Imagine", "John Lennon", 1971, "Classic Rock", 2, "Easy", "Group", "Mid", 5, "Simple, slow, and it lands every time."),
    ("Bridge Over Troubled Water", "Simon & Garfunkel", 1970, "Folk", 3, "Hard", "Solo", "Wide", 4, "Starts as a whisper, ends as a wall. Massive final verse."),
    ("The Sound of Silence", "Simon & Garfunkel", 1964, "Folk", 2, "Medium", "Duet", "Mid", 4, "Hello darkness. Beautiful in two-part harmony."),
    ("Hotel California", "Eagles", 1976, "Classic Rock", 3, "Medium", "Group", "Mid", 5, "Long outro. Let the guitar solo play; nobody minds."),
    ("Desperado", "Eagles", 1973, "Country Rock", 2, "Hard", "Solo", "Wide", 4, "Slow and exposed. Only if the room is listening."),
    ("Stairway to Heaven", "Led Zeppelin", 1971, "Classic Rock", 3, "Legend", "Group", "Wide", 4, "Eight minutes that build to a scream. A commitment."),
    ("Free Bird", "Lynyrd Skynyrd", 1973, "Southern Rock", 4, "Legend", "Group", "Mid-High", 4, "Someone always shouts for it. Someone should finally sing it."),
    ("November Rain", "Guns N' Roses", 1991, "Power Ballad", 4, "Legend", "Solo", "High", 4, "Nine minutes. Three solos. An entire evening in one track."),
    ("Nothing Else Matters", "Metallica", 1991, "Rock Ballad", 3, "Medium", "Group", "Low-Mid", 4, "Surprisingly low and singable. Great for a tired voice."),
    ("Wind of Change", "Scorpions", 1990, "Rock Ballad", 3, "Medium", "Group", "Mid", 4, "The whistle intro alone gets a cheer."),
    ("Always", "Bon Jovi", 1994, "Power Ballad", 4, "Hard", "Solo", "High", 4, "Raspy, enormous, and unashamedly dramatic."),
    ("Bed of Roses", "Bon Jovi", 1992, "Power Ballad", 3, "Hard", "Solo", "Mid-High", 4, "Slow-burn 90s ballad. Big final chorus."),
    ("Open Arms", "Journey", 1981, "Power Ballad", 3, "Hard", "Solo", "High", 4, "Steve Perry's range is not a suggestion. Beautiful if it lands."),
    ("Faithfully", "Journey", 1983, "Power Ballad", 3, "Hard", "Group", "High", 5, "The 'whoa-oh-oh' ending turns everyone into a backing vocalist."),
    ("Every Breath You Take", "The Police", 1983, "New Wave", 3, "Medium", "Solo", "Mid", 5, "Everyone knows it. Nobody notices it's about stalking."),
    ("Don't Look Back in Anger", "Oasis", 1995, "Britpop", 4, "Medium", "Group", "Mid-High", 5, "The definitive arms-around-shoulders closer."),
    ("Champagne Supernova", "Oasis", 1995, "Britpop", 3, "Medium", "Group", "Mid", 4, "Hazy and huge. Perfect for the last-song-of-the-night haze."),
    ("Angels", "Robbie Williams", 1997, "Pop Ballad", 4, "Medium", "Group", "Mid-High", 5, "In the UK this is basically the national anthem at closing time."),
    ("Fix You", "Coldplay", 2005, "Alt Rock", 4, "Medium", "Group", "Mid-High", 5, "Quiet, then enormous. Save it for the very end."),
    ("Viva La Vida", "Coldplay", 2008, "Alt Rock", 4, "Medium", "Group", "Mid-High", 5, "Triumphant. The 'oh-oh-oh' section is a group hug."),
    ("Chasing Cars", "Snow Patrol", 2006, "Alt Rock", 3, "Easy", "Group", "Mid", 5, "Three chords, all the feelings. Very hard to get wrong."),
    ("Iris", "Goo Goo Dolls", 1998, "Alt Rock", 4, "Hard", "Solo", "High", 5, "'And I don't want the world to see me' — everyone joins in."),
    ("I Don't Want to Miss a Thing", "Aerosmith", 1998, "Power Ballad", 4, "Hard", "Solo", "High", 5, "Peak 90s melodrama. Absolutely go for the big note."),
    ("(Everything I Do) I Do It for You", "Bryan Adams", 1991, "Power Ballad", 3, "Medium", "Solo", "Mid-High", 4, "Gravelly and sincere. A dependable slow closer."),
    ("Careless Whisper", "George Michael", 1984, "Pop Soul", 3, "Medium", "Solo", "Mid", 5, "The sax intro gets a bigger reaction than the vocal."),
    ("Against All Odds", "Phil Collins", 1984, "Power Ballad", 3, "Hard", "Solo", "High", 4, "'Take a look at me now' sits brutally high. Worth it."),
    ("In the Air Tonight", "Phil Collins", 1981, "Rock", 3, "Medium", "Group", "Low-Mid", 5, "Everyone waits four minutes to air-drum. Give them that."),
    ("Closing Time", "Semisonic", 1998, "Alt Rock", 4, "Easy", "Group", "Mid", 5, "Literally about the lights coming on. Use it correctly."),
    ("Last Dance", "Donna Summer", 1978, "Disco", 4, "Medium", "Group", "Mid-High", 4, "Slow intro, disco explosion. One final dance."),
    ("The Rose", "Bette Midler", 1979, "Ballad", 2, "Medium", "Solo", "Mid", 4, "Tender and timeless. Lets the room breathe out."),
    ("Wind Beneath My Wings", "Bette Midler", 1988, "Ballad", 3, "Hard", "Solo", "High", 4, "Sentimental in the best way. Big lift at the end."),
    ("Endless Love", "Diana Ross & Lionel Richie", 1981, "Soul Ballad", 2, "Medium", "Duet", "Mid-High", 4, "The definitive slow duet. Eye contact optional."),
    ("Unchained Melody", "The Righteous Brothers", 1965, "Soul", 3, "Hard", "Solo", "Wide", 5, "That climb near the end is one of the great karaoke moments."),
    ("Can't Help Falling in Love", "Elvis Presley", 1961, "Ballad", 2, "Easy", "Group", "Mid", 5, "Short, sweet, and everyone sways. Ideal true-final song."),
    ("Suspicious Minds", "Elvis Presley", 1969, "Rock Soul", 4, "Medium", "Group", "Mid", 4, "Caught in a trap. Bigger energy than most closers."),
    ("What a Wonderful World", "Louis Armstrong", 1967, "Jazz", 2, "Easy", "Group", "Low", 5, "Growl it. Nobody expects Louis; everybody smiles."),
    ("Somewhere Over the Rainbow", "Israel Kamakawiwo'ole", 1993, "Folk", 2, "Easy", "Solo", "Mid", 5, "The ukulele version. Gentle landing for a long night."),
    ("Nothing Compares 2 U", "Sinead O'Connor", 1990, "Pop Ballad", 3, "Hard", "Solo", "Mid-High", 4, "Stark and heartbreaking. Needs a quiet room."),
    ("All by Myself", "Celine Dion", 1996, "Power Ballad", 4, "Legend", "Solo", "Wide", 5, "The final note is a public act of courage."),
    ("My Heart Will Go On", "Celine Dion", 1997, "Power Ballad", 4, "Hard", "Group", "High", 5, "Flute intro, instant recognition, arms out at the front of the ship."),
    ("Un-Break My Heart", "Toni Braxton", 1996, "R&B Ballad", 3, "Hard", "Solo", "Low-Mid", 4, "Rich and low. Rewards a smoky voice."),
    ("Hero", "Mariah Carey", 1993, "Pop Ballad", 3, "Hard", "Solo", "Wide", 5, "Builds to a genuine belter. Classic closing-time choice."),
    ("Without You", "Mariah Carey", 1994, "Power Ballad", 3, "Legend", "Solo", "Wide", 4, "Enormous. Do not attempt on a tired voice."),
    ("And I Am Telling You I'm Not Going", "Jennifer Hudson", 2006, "Soul", 4, "Legend", "Solo", "Wide", 5, "The most demanding song on this list. Standing ovation if you land it."),
    ("When I Was Your Man", "Bruno Mars", 2012, "Pop Ballad", 3, "Hard", "Solo", "High", 5, "Piano and regret. Everyone goes quiet for this one."),
    ("Someone You Loved", "Lewis Capaldi", 2018, "Pop Ballad", 3, "Hard", "Solo", "Mid-High", 5, "Modern gut-punch. The last chorus is a proper climb."),
    ("Stay With Me", "Sam Smith", 2014, "Soul Pop", 3, "Medium", "Group", "Mid-High", 5, "Gospel-choir chorus. The room becomes the choir."),
    ("All of Me", "John Legend", 2013, "Pop Ballad", 3, "Hard", "Solo", "Mid-High", 5, "Beautiful and very exposed. Piano-bar perfection."),
    ("Truly Madly Deeply", "Savage Garden", 1997, "Pop Ballad", 3, "Medium", "Solo", "Mid-High", 4, "90s romance at full volume. Ages surprisingly well."),
    ("Right Here Waiting", "Richard Marx", 1989, "Power Ballad", 3, "Medium", "Solo", "Mid-High", 5, "A karaoke institution. Everybody knows the chorus."),
    ("Time After Time", "Cyndi Lauper", 1983, "Pop", 2, "Easy", "Group", "Mid", 5, "Soft, warm, and easy on a tired voice."),
    ("Under the Bridge", "Red Hot Chili Peppers", 1991, "Alt Rock", 3, "Medium", "Group", "Mid", 4, "The choir outro is a great final singalong."),
    ("Wonderful Tonight", "Eric Clapton", 1977, "Soft Rock", 2, "Easy", "Solo", "Mid", 4, "Slow-dance closer. Almost impossible to strain on."),
    ("Tears in Heaven", "Eric Clapton", 1992, "Soft Rock", 2, "Medium", "Solo", "Mid", 4, "Delicate and quiet. Only for a respectful room."),
    ("Nothing's Gonna Stop Us Now", "Starship", 1987, "Power Ballad", 4, "Hard", "Duet", "High", 4, "Cheesy, soaring, and a brilliant two-hander finish."),
    ("Don't Stop Me Now", "Queen", 1978, "Rock", 5, "Hard", "Group", "High", 5, "Technically a hype song, but an unbeatable final encore."),
]

CATEGORIES = [
    ("Warm-Up", "Start of the Evening", WARM_UP),
    ("Hype", "Middle of the Evening", HYPE),
    ("Closer", "End of the Evening", CLOSERS),
]
